//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tms_webapi_
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.training_enrolled = new HashSet<training_enrolled>();
        }
    
        public int id { get; set; }
        public string email_id { get; set; }
        public string C_password { get; set; }
        public string C_name { get; set; }
        public Nullable<bool> gender { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string phone_no { get; set; }
        public Nullable<int> manager_id { get; set; }
    
        public virtual manager manager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<training_enrolled> training_enrolled { get; set; }
    }
}
