//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tms_webapi_
{
    using System;
    using System.Collections.Generic;
    
    public partial class training_enrolled
    {
        public int id { get; set; }
        public Nullable<int> training_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public string feedback { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual training training { get; set; }
    }
}
