// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace tms_testing
{
    public partial class TrainingEnrolled
    {
        public int Id { get; set; }
        public int? TrainingId { get; set; }
        public int? EmployeeId { get; set; }
        public string Feedback { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual Training Training { get; set; }
    }
}