//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tms_unittesting
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class training_management_systemEntities : DbContext
    {
        public training_management_systemEntities()
            : base("name=training_management_systemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<hr> hrs { get; set; }
        public virtual DbSet<manager> managers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<training> trainings { get; set; }
        public virtual DbSet<training_enrolled> training_enrolled { get; set; }
        public virtual DbSet<training_requests> training_requests { get; set; }
    }
}
