// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tms_lib
{
    public partial class Feedback
    {
        public int Feedbackid { get; set; }
        public string Username { get; set; }
        public string Mailid { get; set; }
        public string Msg { get; set; }
    }
}