// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tms_lib
{
    public partial class Manager
    {
        public Manager()
        {
            Employees = new HashSet<Employee>();
        }

        public int Id { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public bool? Gender { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string PhoneNo { get; set; }
        public int? HrId { get; set; }

        public virtual Hr Hr { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}