// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tms_lib
{
    public partial class TrainingRequest
    {
        public int Id { get; set; }
        public int? TrainingId { get; set; }
        public string EmployeeEmail { get; set; }
        public bool? ApprovalStatus { get; set; }
        public string RejectionReason { get; set; }

        public virtual Employee EmployeeEmailNavigation { get; set; }
        public virtual Training Training { get; set; }
    }
}