// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tms_lib
{
    public partial class Training
    {
        public Training()
        {
            TrainingEnrolleds = new HashSet<TrainingEnrolled>();
            TrainingRequests = new HashSet<TrainingRequest>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime? Startdate { get; set; }
        public DateTime? Enddate { get; set; }
        public string CourseDescription { get; set; }

        public virtual ICollection<TrainingEnrolled> TrainingEnrolleds { get; set; }
        public virtual ICollection<TrainingRequest> TrainingRequests { get; set; }
    }
}